### ISSUE TITLE
Latency is sub-optimal

### ISSUE THREAD

**Issue by bootsector** [bootsector/ControlaBLE#1]
Fast polling ON (1ms):

https://i.imgur.com/ydarmDT.png

Comparing with XBSX controller via BT:

https://i.imgur.com/Heh9se8.png

Fast polling OFF:

https://i.imgur.com/mT8RkZf.png

**Comment by sorgelig** [comment]
what is fast polling here? Is it feature of your firmware to poll the joystick using SNES serial bus?

**Comment by bootsector** [comment]
Latency measure procedure is performed by @misteraddons on the MiSTer FPGA with USB fast polling on active, as described here:

https://docs.google.com/spreadsheets/d/1KlRObr3Be4zLch7Zyqg6qCJzGuhyGmXaOIUrpfncXIM/edit#gid=369482991

SNES controllers are polled in a free loop in the usual way as seen here:

https://github.com/bootsector/ControllaBLE/blob/master/src/snes.cpp

**Comment by bootsector** [comment]
The lag test method was designed for wired USB controllers in mind. Not sure how fast usb polling on MiSTer affects reading BT dongles though.

**Comment by sorgelig** [comment]
then probably fast USB polling add hickup to the system..
It may also depend how many USB devices are connected.

**Comment by bootsector** [comment]
Yeah. Those numbers are really odd, as the actual feeling is that there's no lag at all.

**Comment by sorgelig** [comment]
Ordered some ESP32 modules with battery LiPo charger integrated.
Almost bought ESP32-S2 board but noticed it misses BT. Thought it was some mistake but it turned out ESP32-S2 chip really doesn't have BT! That's the weirdest move they could do... BLE is one of most used connections in IoT where this chip is positioned... The only thing they should do is to replace one UART (no one will cry about CAN/ETH omission too) with USB to make a perfect single-chip solution, but they again ruined the idea..

**Comment by bootsector** [comment]
I'm closing this as subjective perceivable lag has been none and the experience doesn't reflect at all the numbers shown above.
